# -*- coding: utf-8 -*-
"""latihan_modeldeploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gfmMMzsyE481q4rQnC5HcDs2cRZ9sue
"""

import seaborn as sns

import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn import datasets

df = sns.load_dataset('iris')
df.head()

class IrisClassifier:
    def __init__(self, n_neighbors=5):
        self.n_neighbors = n_neighbors
        self.model = KNeighborsClassifier(n_neighbors=self.n_neighbors)
        self.scaler = StandardScaler()
        self.load_data()

    def load_data(self):
        iris = datasets.load_iris()
        self.X = iris.data
        self.y = iris.target

        # Split data menjadi train & test
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
            self.X, self.y, test_size=0.2, random_state=42)

    def preprocess_data(self):
        self.X_train = self.scaler.fit_transform(self.X_train)
        self.X_test = self.scaler.transform(self.X_test)

    def train(self):
        self.preprocess_data()
        self.model.fit(self.X_train, self.y_train)

    def evaluate(self):
        y_pred = self.model.predict(self.X_test)
        acc = accuracy_score(self.y_test, y_pred)
        report = classification_report(self.y_test, y_pred)
        print(f"Akurasi Model: {acc:.4f}\n")
        print("Laporan Klasifikasi:")
        print(report)

    def predict(self, data):
        data = np.array(data).reshape(1, -1)
        data = self.scaler.transform(data)
        return self.model.predict(data)

def save_model(self, filename="iris_model.pkl"):
        """Menyimpan model ke dalam file pickle."""
        with open(filename, "wb") as file:
            pickle.dump((self.model, self.scaler), file)
        print(f"Model disimpan sebagai {filename}")

@staticmethod
    def load_model(filename="iris_model.pkl"):
        """Memuat model dari file pickle."""
        with open(filename, "rb") as file:
            model, scaler = pickle.load(file)
        print(f"Model {filename} berhasil dimuat")

        loaded_classifier = IrisClassifier()
        loaded_classifier.model = model
        loaded_classifier.scaler = scaler
        return loaded_classifier

classifier = IrisClassifier(n_neighbors=3)
classifier.train()
classifier.evaluate()

#save model dengan format pickle
filename = "iris_model.pkl"
pkl.dump(classifier, open(filename, "wb"))

import streamlit as st
import joblib
import numpy as np

# Load the machine learning model
model = joblib.load('RF_class.pkl')

def main():
    st.title('Machine Learning Model Deployment')

    # Add user input components for 5 features
    sepal_length = st.slider('sepal_length', min_value=0.0, max_value=10.0, value=0.1)
    sepal_width = st.slider('sepal_width', min_value=0.0, max_value=10.0, value=0.1)
    patal_length = st.slider('patal_length', min_value=0.0, max_value=10.0, value=0.1)
    patal_width = st.slider('patal_width', min_value=0.0, max_value=10.0, value=0.1)

    if st.button('Make Prediction'):
        features = [sepal_length, sepal_width, patal_length, patal_width]
        result = make_prediction(features)
        st.success(f'The prediction is: {result}')

def make_prediction(features):
    # Use the loaded model to make predictions
    # Replace this with the actual code for your model
    input_array = np.array(features).reshape(1, -1)
    prediction = model.predict(input_array)
    return prediction[0]

if __name__ == '__main__':
    main()